# Generated by Django 4.1.4 on 2022-12-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
