# Generated by Django 4.1.4 on 2022-12-31 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('print', models.IntegerField()),
                ('address', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.product')),
            ],
        ),
    ]
