# Generated by Django 4.1.4 on 2022-12-31 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='print',
            new_name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
